/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parking.management;

import java.util.Calendar;

/**
 *
 * @author aditya
 */
public class delete extends java.awt.Frame {

    /**
     * Creates new form delete
     */
      Calendar cal=Calendar.getInstance();

      int pi= cal.get(Calendar.HOUR_OF_DAY);
    int  mi= cal.get(Calendar.MINUTE);
    String dip;
    int p;
String []s;
String []fine;
     
    public delete() {
        initComponents();
        String dip= pi+":"+mi;
       exitd.setText(dip);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        platelb = new javax.swing.JLabel();
        zonelb = new javax.swing.JLabel();
        platenod = new javax.swing.JTextField();
        namelb = new javax.swing.JLabel();
        expdep = new javax.swing.JLabel();
        entrylbl = new javax.swing.JLabel();
        exitlb = new javax.swing.JLabel();
        arrivald = new javax.swing.JTextField();
        departured = new javax.swing.JTextField();
        named = new javax.swing.JTextField();
        exitd = new javax.swing.JTextField();
        confirmd = new javax.swing.JButton();
        homed = new javax.swing.JButton();
        findd = new javax.swing.JButton();
        statusd = new javax.swing.JTextField();
        zonenod = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        platelb.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        platelb.setForeground(new java.awt.Color(255, 255, 255));
        platelb.setText("ZONE NO:");
        jPanel1.add(platelb, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 70, -1));

        zonelb.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        zonelb.setForeground(new java.awt.Color(255, 255, 255));
        zonelb.setText("PLATE NO:");
        jPanel1.add(zonelb, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 80, -1));

        platenod.setEditable(false);
        platenod.setBackground(new java.awt.Color(0, 0, 1));
        platenod.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        platenod.setForeground(new java.awt.Color(255, 255, 255));
        platenod.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(platenod, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 220, -1));

        namelb.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        namelb.setForeground(new java.awt.Color(255, 255, 255));
        namelb.setText("NAME:");
        jPanel1.add(namelb, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 60, -1));

        expdep.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        expdep.setForeground(new java.awt.Color(255, 255, 255));
        expdep.setText("DEPARTURE:");
        jPanel1.add(expdep, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 121, 27));

        entrylbl.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        entrylbl.setForeground(new java.awt.Color(255, 255, 255));
        entrylbl.setText("ARRIVAL:");
        jPanel1.add(entrylbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 121, 27));

        exitlb.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        exitlb.setForeground(new java.awt.Color(255, 255, 255));
        exitlb.setText("EXIT TIME:");
        jPanel1.add(exitlb, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 121, 27));

        arrivald.setEditable(false);
        arrivald.setBackground(new java.awt.Color(0, 0, 1));
        arrivald.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        arrivald.setForeground(new java.awt.Color(255, 255, 255));
        arrivald.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        arrivald.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrivaldActionPerformed(evt);
            }
        });
        jPanel1.add(arrivald, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 220, -1));

        departured.setEditable(false);
        departured.setBackground(new java.awt.Color(0, 0, 1));
        departured.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        departured.setForeground(new java.awt.Color(255, 255, 255));
        departured.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        departured.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departuredActionPerformed(evt);
            }
        });
        jPanel1.add(departured, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 220, -1));

        named.setEditable(false);
        named.setBackground(new java.awt.Color(0, 0, 1));
        named.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        named.setForeground(new java.awt.Color(255, 255, 255));
        named.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        named.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namedActionPerformed(evt);
            }
        });
        jPanel1.add(named, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 220, -1));

        exitd.setEditable(false);
        exitd.setBackground(new java.awt.Color(0, 0, 1));
        exitd.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        exitd.setForeground(new java.awt.Color(255, 255, 255));
        exitd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        exitd.setText(" ");
        exitd.setToolTipText("");
        jPanel1.add(exitd, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 220, -1));

        confirmd.setBackground(new java.awt.Color(0, 0, 1));
        confirmd.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        confirmd.setForeground(new java.awt.Color(255, 255, 255));
        confirmd.setText("CONFIRM");
        confirmd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmdActionPerformed(evt);
            }
        });
        jPanel1.add(confirmd, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 120, 20));

        homed.setBackground(new java.awt.Color(0, 0, 1));
        homed.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        homed.setForeground(new java.awt.Color(255, 255, 255));
        homed.setText("HOME");
        homed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homedActionPerformed(evt);
            }
        });
        jPanel1.add(homed, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, -1, 20));

        findd.setBackground(new java.awt.Color(0, 0, 1));
        findd.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        findd.setForeground(new java.awt.Color(255, 255, 255));
        findd.setText("FIND");
        findd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finddActionPerformed(evt);
            }
        });
        jPanel1.add(findd, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 80, 20));

        statusd.setEditable(false);
        statusd.setBackground(new java.awt.Color(0, 0, 1));
        statusd.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        statusd.setForeground(new java.awt.Color(255, 255, 255));
        statusd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(statusd, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 320, -1));

        zonenod.setBackground(new java.awt.Color(0, 0, 1));
        zonenod.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        zonenod.setForeground(new java.awt.Color(255, 255, 255));
        zonenod.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(zonenod, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 220, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parking/management/9.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void arrivaldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrivaldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arrivaldActionPerformed

    private void finddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finddActionPerformed
        // TODO add your handling code here:
       
        p= Integer.parseInt(zonenod.getText());
             priority h=new priority();
      s= h.find(p);
      if(s[0]!="1")
      {
          
        System.out.println("delete"+s);
          platenod.setText(s[3]);
        named.setText(s[0]);
  
    arrivald.setText(s[1]);
  
     departured.setText(s[2]);
         statusd.setText("ALLCLEAR");
      }

        if(s[0]=="1")
        {
        finelink fl=new finelink();
        fine =fl.find(p);
        if(fine[0]!="2")
        {
        System.out.println("lenght"+fine.length);
         statusd.setText("FINE");
         System.out.println("delete"+s);
          platenod.setText(fine[3]);
        named.setText(fine[0]);
  
    arrivald.setText(fine[1]);
  
     departured.setText(fine[2]);
        }
       else
        {
        
         statusd.setText("ERROR");
           platenod.setText(" ");
        named.setText(" ");
  
    arrivald.setText(" ");
  
     departured.setText(" ");


        }
        
        } 
    }//GEN-LAST:event_finddActionPerformed
    

    private void confirmdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmdActionPerformed
        // TODO add your handling code here:
        if(s[0]!="1")
        {
                priority.deletespecific(p);
                statusd.setText("AMMOUNT PAID");
        }
      
        if(s[0]=="1")
        {
            finelink fl=new finelink();
            fl.deletespecific(p);
            statusd.setText("FINE+AMMOUNT PAID ");
        }
        
        if(fine[0]=="2")
        {
            statusd.setText("ALREADY EMPTY");
        }
        
        vacant.empupdate(p);
    }//GEN-LAST:event_confirmdActionPerformed

    private void homedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homedActionPerformed
        // TODO add your handling code here:
         new NewFrame1().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homedActionPerformed

    private void departuredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departuredActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departuredActionPerformed

    private void namedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new delete().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField arrivald;
    private javax.swing.JButton confirmd;
    public static javax.swing.JTextField departured;
    private javax.swing.JLabel entrylbl;
    private javax.swing.JTextField exitd;
    private javax.swing.JLabel exitlb;
    private javax.swing.JLabel expdep;
    private javax.swing.JButton findd;
    private javax.swing.JButton homed;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField named;
    private javax.swing.JLabel namelb;
    private javax.swing.JLabel platelb;
    public static volatile javax.swing.JTextField platenod;
    private javax.swing.JTextField statusd;
    private javax.swing.JLabel zonelb;
    private javax.swing.JTextField zonenod;
    // End of variables declaration//GEN-END:variables

  
}
