/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parking.management;

import java.awt.Color;

/**
 *
 * @author aditya
 */

public class NewFrame1 extends java.awt.Frame {

    /**
     * Creates new form NewFrame1
     */
    int f=0;
    public NewFrame1() {
        initComponents();
        //txtvacant.setBackground(new java.awt.Color(0,0,0,1));
        //txtdelete.setBackground(new java.awt.Color(0,0,0,1));
        //txthistory.setBackground(new java.awt.Color(0,0,0,1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        txtvacant = new javax.swing.JButton();
        txtdelete = new javax.swing.JButton();
        txthistory = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setToolTipText("");
        jPanel1.setAutoscrolls(true);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtvacant.setBackground(new java.awt.Color(0, 0, 0, 80));
        txtvacant.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        txtvacant.setForeground(new java.awt.Color(255, 255, 255));
        txtvacant.setText("VACANT");
        txtvacant.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtvacant.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtvacant.setFocusPainted(false);
        txtvacant.setFocusable(false);
        txtvacant.setRequestFocusEnabled(false);
        txtvacant.setRolloverEnabled(false);
        txtvacant.setVerifyInputWhenFocusTarget(false);
        txtvacant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvacantActionPerformed(evt);
            }
        });
        jPanel1.add(txtvacant, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 190, -1));

        txtdelete.setBackground(new java.awt.Color(0, 0, 0, 80));
        txtdelete.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        txtdelete.setForeground(new java.awt.Color(255, 255, 255));
        txtdelete.setText("DELETE VEHICLE");
        txtdelete.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtdelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtdelete.setFocusPainted(false);
        txtdelete.setFocusable(false);
        txtdelete.setRequestFocusEnabled(false);
        txtdelete.setRolloverEnabled(false);
        txtdelete.setVerifyInputWhenFocusTarget(false);
        txtdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdeleteActionPerformed(evt);
            }
        });
        jPanel1.add(txtdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 190, -1));

        txthistory.setBackground(new java.awt.Color(0, 0, 0, 80));
        txthistory.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        txthistory.setForeground(new java.awt.Color(255, 255, 255));
        txthistory.setText("HISTORY");
        txthistory.setActionCommand("History");
        txthistory.setAutoscrolls(true);
        txthistory.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txthistory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txthistory.setFocusPainted(false);
        txthistory.setFocusable(false);
        txthistory.setRequestFocusEnabled(false);
        txthistory.setRolloverEnabled(false);
        txthistory.setVerifyInputWhenFocusTarget(false);
        txthistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthistoryActionPerformed(evt);
            }
        });
        jPanel1.add(txthistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 190, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parking/management/5.jpg"))); // NOI18N
        jLabel2.setFocusable(false);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void txtvacantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvacantActionPerformed
        // TODO add your handling code here:
                new vacant().setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_txtvacantActionPerformed

    private void txtdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdeleteActionPerformed
        // TODO add your handling code here:
          new delete().setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_txtdeleteActionPerformed

    private void txthistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthistoryActionPerformed
        // TODO add your handling code here:
         new viewlink().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_txthistoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewFrame1().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton txtdelete;
    private javax.swing.JButton txthistory;
    private javax.swing.JButton txtvacant;
    // End of variables declaration//GEN-END:variables
}
