package parking.management;

import java.util.Calendar;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author 63968
 */
public class receipt extends javax.swing.JPanel {

     Calendar cal=Calendar.getInstance();

      int pi= cal.get(Calendar.HOUR_OF_DAY);
    int  mi= cal.get(Calendar.MINUTE);
    String dip;
    int p;
String []s;
    /**
     * Creates new form receipt
     */
    public receipt() {
        initComponents();
    String dip= pi+":"+mi;
       //exitreceipt.setText(dip);
       
        
    }
         /**
          * This method is called from within the constructor to initialize the form.
          * WARNING: Do NOT modify this code. The content of this method is always
          * regenerated by the Form Editor.
          */
         // <editor-fold defaultstate="collapsed" desc="Generated Code">
         /**
          * Exit the Application
          */
         /**
          * This method is called from within the constructor to initialize the form.
          * WARNING: Do NOT modify this code. The content of this method is always
          * regenerated by the Form Editor.
          */
         /**
          * This method is called from within the constructor to initialize the form.
          * WARNING: Do NOT modify this code. The content of this method is always
          * regenerated by the Form Editor.
          */
         // <editor-fold defaultstate="collapsed" desc="Generated Code">
         /**
          * Exit the Application
          */
         /**
          * This method is called from within the constructor to initialize the form.
          * WARNING: Do NOT modify this code. The content of this method is always
          * regenerated by the Form Editor.
          */
         /**
          * This method is called from within the constructor to initialize the form.
          * WARNING: Do NOT modify this code. The content of this method is always
          * regenerated by the Form Editor.
          */
         // <editor-fold defaultstate="collapsed" desc="Generated Code">
         /**
          * Exit the Application
          */
         /**
          * This method is called from within the constructor to initialize the form.
          * WARNING: Do NOT modify this code. The content of this method is always
          * regenerated by the Form Editor.
          */
         /**
          * This method is called from within the constructor to initialize the form.
          * WARNING: Do NOT modify this code. The content of this method is always
          * regenerated by the Form Editor.
          */
         // <editor-fold defaultstate="collapsed" desc="Generated Code">
         /**
          * Exit the Application
          */
         /**
          * This method is called from within the constructor to initialize the form.
          * WARNING: Do NOT modify this code. The content of this method is always
          * regenerated by the Form Editor.
          */
         /**
          * This method is called from within the constructor to initialize the form.
          * WARNING: Do NOT modify this code. The content of this method is always
          * regenerated by the Form Editor.
          */
         // <editor-fold defaultstate="collapsed" desc="Generated Code">
         /**
          * Exit the Application
          */
         /**
          * This method is called from within the constructor to initialize the form.
          * WARNING: Do NOT modify this code. The content of this method is always
          * regenerated by the Form Editor.
          */
         /**
          * This method is called from within the constructor to initialize the form.
          * WARNING: Do NOT modify this code. The content of this method is always
          * regenerated by the Form Editor.
          */
         // <editor-fold defaultstate="collapsed" desc="Generated Code">
         /**
          * Exit the Application
          */
         /**
          * This method is called from within the constructor to initialize the form.
          * WARNING: Do NOT modify this code. The content of this method is always
          * regenerated by the Form Editor.
          */
         /**
          * This method is called from within the constructor to initialize the form.
          * WARNING: Do NOT modify this code. The content of this method is always
          * regenerated by the Form Editor.
          */
         // <editor-fold defaultstate="collapsed" desc="Generated Code">
         /**
          * Exit the Application
          */
         /**
          * This method is called from within the constructor to initialize the form.
          * WARNING: Do NOT modify this code. The content of this method is always
          * regenerated by the Form Editor.
          */    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                         
    /**
     * Exit the Application
     */


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtnameR = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtdateR = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtplatenoR = new javax.swing.JLabel();
        txtarrivalR = new javax.swing.JLabel();
        txtdepartureR = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        exitreceipt = new javax.swing.JButton();
        show = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel3.setText("=============================");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, 20));

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 8)); // NOI18N
        jLabel4.setText("40th Street, Taguig, 1634 Metro Manila");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, 10));

        jLabel6.setFont(new java.awt.Font("Consolas", 0, 8)); // NOI18N
        jLabel6.setText("0945-801-4367");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        jLabel8.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        jLabel8.setText("PLATE NO");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        jLabel12.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel12.setText("=============================");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, 30));

        jLabel11.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        jLabel11.setText("DATE");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        jLabel9.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        jLabel9.setText("ARRIVAL TIME");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        txtnameR.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        add(txtnameR, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        jLabel10.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        jLabel10.setText("DEPARTURE TIME");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        txtdateR.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        add(txtdateR, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 50, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parking/management/barcode-3-removebg-preview (2).png"))); // NOI18N
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));

        jLabel7.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        jLabel7.setText("NAME");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        txtplatenoR.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        add(txtplatenoR, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

        txtarrivalR.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        txtarrivalR.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        add(txtarrivalR, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 50, -1));

        txtdepartureR.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        add(txtdepartureR, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 50, -1));

        jLabel15.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        jLabel15.setText(":");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 10, 10));

        jLabel17.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        jLabel17.setText(":");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 10, 10));

        jLabel19.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        jLabel19.setText(":");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 10, 10));

        jLabel5.setFont(new java.awt.Font("Consolas", 0, 8)); // NOI18N
        jLabel5.setText("enaphie@gmail.com");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        jLabel18.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        jLabel18.setText(":");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 10, 10));

        jLabel16.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        jLabel16.setText(":");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 10, 10));

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jLabel1.setText("ENAPHIE PARKING SPACE");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 150, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parking/management/images-removebg-preview (1).png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 320, 420));

        jLabel14.setText("jLabel14");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        exitreceipt.setText("EXIT");
        add(exitreceipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, -1, -1));

        show.setText("SHOW");
        add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
/*private void showActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
         priority x=new priority();
          s= x.show(p);
     
          
      //  System.out.println("delete"+s);
          txtplatenoR.setText(s[3]);
        txtnameR.setText(s[0]);
  
    txtarrivalR.setText(s[1]);
  
     txtdepartureR.setText(s[2]);
        
   
    }   */
    private void exitreceiptActionPerformed(java.awt.event.ActionEvent evt) { 
    new delete().setVisible(true);
        this.setVisible(false);
}

public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new receipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitreceipt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton show;
    private javax.swing.JLabel txtarrivalR;
    private javax.swing.JLabel txtdateR;
    private javax.swing.JLabel txtdepartureR;
    private javax.swing.JLabel txtnameR;
    private javax.swing.JLabel txtplatenoR;
    // End of variables declaration//GEN-END:variables

}  
